skillMetadata:
   sections:
      - name: Login
        fields:
          - name: username
            type: username
            label: hdm-email
            value: "bw040@hdm-stuttgart.de"
      - name: PASSWORT
        fields:
          - name: password
            type: password
            label: password
            value: "beckerasano2"
      - name: url
        fields:
          - name: url
            type: text
            label: calender-url
            value: "https://nextcloud.humanoidlab.hdm-stuttgart.de/remote.php/dav/calendars/bw040@hdm-stuttgart.de/personal/"
