skillMetadata:
   sections:
      - name: USERNAME
        fields:
          - name: my_email_address
            type: email
            label: Enter your email address
            value:
      - name: PASSWORT
        fields:
          - name: my_password
            type: password
            label: Enter your password
            value: