skillMetadata:
   sections:
      - name: USERNAME
        fields:
          - name: my_email_address
            type: email
            label: Enter your email address
            value: "bw040@hdm-stuttgart.de"
      - name: PASSWORT
        fields:
          - name: my_password
            type: password
            label: Enter your password
            value: "beckerasano2"
      - name: URL
        fields:
          - name: url
            type: text
            label: enter calendar url
            value: "https://nextcloud.humanoidlab.hdm-stuttgart.de/remote.php/dav/calendars/bw040@hdm-stuttgart.de/personal/"
