skillMetadata:
   sections:
      - name: Login
        fields:
          - name: username
            type: username
            label: hdm-email
            value:
      - name: PASSWORT
        fields:
          - name: password
            type: password
            label: password
            value:
      - name: url
        fields:
          - name: url
            type: text
            label: calender-url
            value:
